In [1]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt

In [79]:
data = pd.read_csv('Q2_LogR_X9.csv',header=None, names=('X1','X2','X3','X4','X5','X6','X7','X8','X9','Y'))
data

    X1  X2  X3  X4  X5  X6  X7  X8  X9  Y
0    8  10  10   8   7  10   9   7   1  4
1    5   3   3   3   2   3   4   4   1  4
2    1   1   1   1   2   3   3   1   1  2
3    8   7   5  10   7   9   5   5   4  4
4    7   4   6   4   6   1   4   3   1  4
5    4   1   1   1   2   1   2   1   1  2
6    4   1   1   1   2   1   3   1   1  2
7   10   7   7   6   4  10   4   1   2  4
8    6   1   1   1   2   1   3   1   1  2
9    7   3   2  10   5  10   5   4   4  4
10  10   5   5   3   6   7   7  10   1  4
11   3   1   1   1   2   1   2   1   1  2
12   8   4   5   1   2   5   7   3   1  4
13   1   1   1   1   2   1   3   1   1  2
14   5   2   3   4   2   7   3   6   1  4
15   3   2   1   1   1   1   2   1   1  2
16   5   1   1   1   2   1   2   1   1  2
17   2   1   1   1   2   1   2   1   1  2
18   1   1   3   1   2   1   1   1   1  2
19   3   1   1   1   1   1   2   1   1  2
20   2   1   1   1   2   1   3   1   1  2
21  10   7   7   3   8   5   7   4   3  4
22   2   1   1   2   2   1   3   1   1  2
23   3   1   2   1   2   1   2   1   1  2
24   2   1   1   1   2   1   2   1   1  2
25  10  10  10   8   6   1   8   9   1  4
26   6   2   1   1   1   1   7   1   1  2
27   5   4   4   9   2  10   5   6   1  4
28   2   5   3   3   6   7   7   5   1  4
29  10   4   3   1   3   3   6   5   2  4
30   6  10  10   2   8  10   7   3   3  4
31   5   6   5   6  10   1   3   1   1  4
32  10  10  10   4   8   1   8  10   1  0
33   6   6   6   9   6   2   7   8   1  0

In [62]:
# creating training and test set without 'train_test_split'
shuffler = rn.sample(range(34),34) #generating 33 random & unique integers
data['new_index'] = shuffler #adding as new column uin the dataset
data.set_index('new_index', inplace=True) #resetting the index

# Finally Sorting the DataFrame according to the new index
data.sort_index(inplace=True)

           X1  X2  X3  X4  X5  X6  X7  X8  X9  Y
new_index
0           1   1   1   1   2   1   3   1   1  2
1           7   4   6   4   6   1   4   3   1  4
2           3   1   2   1   2   1   2   1   1  2
3           6  10  10   2   8  10   7   3   3  4
4           1   1   3   1   2   1   1   1   1  2
5           6   2   1   1   1   1   7   1   1  2
6           3   2   1   1   1   1   2   1   1  2
7           4   1   1   1   2   1   2   1   1  2
8           8   4   5   1   2   5   7   3   1  4
9           2   1   1   1   2   1   2   1   1  2
10          1   1   1   1   2   3   3   1   1  2
11          5   4   4   9   2  10   5   6   1  4
12          2   1   1   1   2   1   2   1   1  2
13          2   1   1   2   2   1   3   1   1  2
14          5   2   3   4   2   7   3   6   1  4
15          5   1   1   1   2   1   2   1   1  2
16         10  10  10   4   8   1   8  10   1  0
17          6   1   1   1   2   1   3   1   1  2
18         10  10  10   8   6   1   8   9   1  4
19          6   6   6   9   6   2   7   8   1  0
20          2   5   3   3   6   7   7   5   1  4
21          4   1   1   1   2   1   3   1   1  2
22          3   1   1   1   2   1   2   1   1  2
23         10   5   5   3   6   7   7  10   1  4
24          8   7   5  10   7   9   5   5   4  4
25          2   1   1   1   2   1   3   1   1  2
26          5   6   5   6  10   1   3   1   1  4
27          8  10  10   8   7  10   9   7   1  4
28         10   7   7   3   8   5   7   4   3  4
29         10   7   7   6   4  10   4   1   2  4
30          3   1   1   1   1   1   2   1   1  2
31          7   3   2  10   5  10   5   4   4  4
32          5   3   3   3   2   3   4   4   1  4
33         10   4   3   1   3   3   6   5   2  4

In [63]:
#scaling and standardizing using StandardScaler
from sklearn.preprocessing import StandardScaler
sst = StandardScaler()

#Standardizing the data apart from the Class column
data_scaled = pd.DataFrame(sst.fit_transform(data.drop('Y',axis=1)))

#Adding the Class column back to the DataFrame
data_scaled['Y'] = data.Y

,0,1,2,3,4,5,6,7,8,Y
0,-1.452754,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-0.601938,-0.781556,-0.422159,2
1,0.577122,0.105882,0.791497,0.244056,0.897231,-0.733357,-0.157027,-0.082269,-0.422159,4
2,-0.776129,-0.875932,-0.537436,-0.751694,-0.687489,-0.733357,-1.046848,-0.781556,-0.422159,2
3,0.238809,2.069509,2.120431,-0.419777,1.689591,1.876030,1.177704,-0.082269,1.970073,4
4,-1.452754,-0.875932,-0.205203,-0.751694,-0.687489,-0.733357,-1.491758,-0.781556,-0.422159,2
5,0.238809,-0.548661,-0.869670,-0.751694,-1.083669,-0.733357,1.177704,-0.781556,-0.422159,2
6,-0.776129,-0.548661,-0.869670,-0.751694,-1.083669,-0.733357,-1.046848,-0.781556,-0.422159,2
7,-0.437816,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-1.046848,-0.781556,-0.422159,2
8,0.915434,0.105882,0.459264,-0.751694,-0.687489,0.426370,1.177704,-0.082269,-0.422159,4
9,-1.114442,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-1.046848,-0.781556,-0.422159,2
10,-1.452754,-0.875932,-0.869670,-0.751694,-0.687489,-0.153493,-0.601938,-0.781556,-0.422159,2
11,-0.099504,0.105882,0.127030,1.903640,-0.687489,1.876030,0.287883,0.966661,-0.422159,4
12,-1.114442,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-1.046848,-0.781556,-0.422159,2
13,-1.114442,-0.875932,-0.869670,-0.419777,-0.687489,-0.733357,-0.601938,-0.781556,-0.422159,2
14,-0.099504,-0.548661,-0.205203,0.244056,-0.687489,1.006234,-0.601938,0.966661,-0.422159,4
15,-0.099504,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-1.046848,-0.781556,-0.422159,2
16,1.592060,2.069509,2.120431,0.244056,1.689591,-0.733357,1.622614,2.365234,-0.422159,0
17,0.238809,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-0.601938,-0.781556,-0.422159,2
18,1.592060,2.069509,2.120431,1.571723,0.897231,-0.733357,1.622614,2.015591,-0.422159,4
19,0.238809,0.760424,0.791497,1.903640,0.897231,-0.443425,1.177704,1.665947,-0.422159,0
20,-1.114442,0.433153,-0.205203,-0.087860,0.897231,1.006234,1.177704,0.617018,-0.422159,4
21,-0.437816,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-0.601938,-0.781556,-0.422159,2
22,-0.776129,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-1.046848,-0.781556,-0.422159,2
23,1.592060,0.433153,0.459264,-0.087860,0.897231,1.006234,1.177704,2.365234,-0.422159,4
24,0.915434,1.087696,0.459264,2.235556,1.293411,1.586098,0.287883,0.617018,3.166189,4
25,-1.114442,-0.875932,-0.869670,-0.751694,-0.687489,-0.733357,-0.601938,-0.781556,-0.422159,2
26,-0.099504,0.760424,0.459264,0.907890,2.481951,-0.733357,-0.601938,-0.781556,-0.422159,4
27,0.915434,2.069509,2.120431,1.571723,1.293411,1.876030,2.067524,1.316304,-0.422159,4
28,1.592060,1.087696,1.123731,-0.087860,1.689591,0.426370,1.177704,0.267374,1.970073,4
29,1.592060,1.087696,1.123731,0.907890,0.104871,1.876030,-0.157027,-0.781556,0.773957,4
30,-0.776129,-0.875932,-0.869670,-0.751694,-1.083669,-0.733357,-1.046848,-0.781556,-0.422159,2
31,0.577122,-0.221389,-0.537436,2.235556,0.501051,1.876030,0.287883,0.267374,3.166189,4
32,-0.099504,-0.221389,-0.205203,-0.087860,-0.687489,-0.153493,-0.157027,0.267374,-0.422159,4
33,1.592060,0.105882,-0.205203,-0.751694,-0.291309,-0.153493,0.732793,0.617018,0.773957,4

In [77]:
# Our dataset consists of 32 data points. So splitting it on a 70:30 ratio. 
# You can also some other ratio

# First 27 Data points for Training
data_train = data_scaled.iloc[:32,:]

#Last 5 for Testing
data_test = data_scaled.iloc[32:,:]

In [78]:
# Initializing all the weights as 0
theta0_new, theta1_new, theta2_new, theta3_new, theta4_new, theta5_new, theta6_new, theta7_new, theta8_new, theta9_new = 0,0,0,0,0,0,0,0,0,0

#learning rate
a = 0.02

#sigmoid function (hypothesis)
def sigmoid(output):
    z = 1/(1+math.exp(-output)) 
    return z

for epoch in range(len(data_train)):   
    p_preds = np.array([])
    p_pred_exps = np.array([])
    error = np.array([])
    error_x1 = np.array([])
    error_x2 = np.array([])
    error_x3 = np.array([])
    error_x4 = np.array([])
    error_x5 = np.array([])
    error_x6 = np.array([])
    error_x7 = np.array([])
    error_x8 = np.array([])
    error_x9 = np.array([])
    p_y = np.array([])
    
    # Assigning all the weights their new values after an epoch:
    theta0 = theta0_new
    theta1 = theta1_new
    theta2 = theta2_new
    theta3 = theta3_new
    theta4 = theta4_new
    theta5 = theta5_new
    theta6 = theta6_new
    theta7 = theta7_new
    theta8 = theta8_new
    theta9 = theta9_new

    # Iterating through the Df and calculating all parameters:
    for row in data_train.itertuples():
        #The predicted value:
        p_pred = theta0 + theta1*row[1]+ theta2*row[2] + theta3*row[3] + theta4*row[4] + theta5*row[5] + theta6*row[6] + theta7*row[7] + theta8*row[8] + theta9*row[9]
        p_preds = np.append(p_preds, p_pred)

        # Predicted value after applying the sigmoid function
        p_pred_exp = sigmoid(p_pred)

        p_pred_exps = np.append(p_pred_exps, p_pred_exp)   

        # Bifurcating the predicted class as per its probability to be the default class
        if p_pred_exp > 0.5:
            p_y = np.append(p_y,4)
        else:
            p_y = np.append(p_y,2)
        
    # The error in prediction(1/1-e^-(thet0+...theat9*x9)-y)
    error = p_pred_exps - data_train.Y

    # Pre-calculating the error*x values for all the weights:
    error_x1 = error*data_train[0]
    error_x2 = error*data_train[1]
    error_x3 = error*data_train[2]
    error_x4 = error*data_train[3]
    error_x5 = error*data_train[4]
    error_x6 = error*data_train[5]
    error_x7 = error*data_train[6]
    error_x8 = error*data_train[7]
    error_x9 = error*data_train[8]

    # Calculating Mean Squared Error
    MSE_val = (error).mean()
    MSE = np.append(MSE, MSE_val)

    # Updating the weights (coefficients)
    theta0_new = theta0 - a*np.sum(error)
    theta1_new = theta1 - a*np.sum(error_x1)
    theta2_new = theta2 - a*np.sum(error_x2)
    theta3_new = theta3 - a*np.sum(error_x3)
    theta4_new = theta4 - a*np.sum(error_x4)
    theta5_new = theta5 - a*np.sum(error_x5)
    theta6_new = theta6 - a*np.sum(error_x6)
    theta7_new = theta7 - a*np.sum(error_x7)
    theta8_new = theta8 - a*np.sum(error_x8)
    theta9_new = theta9 - a*np.sum(error_x9)

# Adding the predicted Y as a separate column to check for performance:
data_train['pred_y'] = p_y
for i in range(len(data_train['Y'])):
    if data_train['Y'][i] == 0:
        print(f"predicted value: {data_train['pred_y'][i]}")

<ipython-input-78-4d6dd47fbbd7>:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train['pred_y'] = p_y

predicted value: 4.0
predicted value: 4.0